name: checked-io-example
version: 0.1.0.0

library:
  source-dirs: src
  dependencies:
    - name: base
      mixin:
        - hiding (Prelude)
    - name: checked-io
      mixin:
        - hiding (CheckedIO)
        - (CheckedIO as Prelude)
  when:
    - condition: false
      other-modules: Paths_checked_io_example

executable:
  main: exe/Main.hs
  dependencies:
    - name: base
      mixin:
        - hiding (Prelude)
    - name: checked-io
      mixin:
        - hiding (CheckedIO)
        - (CheckedIO as Prelude)
    - checked-io-example
  when:
    - condition: false
      other-modules: Paths_checked_io_example
